import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { AppDataProvider } from "@/Context/AppDataContext";
import Whatsapp from "@/Components/Whatsapp/Whatsapp";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Example App in NextJS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppDataProvider>
          {children}
          <Whatsapp phoneNumber="5492314613205" positionX="30px" positionY="30px" />
          <Whatsapp phoneNumber="5492314613205" positionX="30px" positionY="120px" />
        </AppDataProvider>
      </body>
    </html>
  );
}
